import { initializeApp } from "https://www.gstatic.com/firebasejs/11.2.0/firebase-app.js";
import {
  onAuthStateChanged,
  getAuth,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  signOut,
} from "https://www.gstatic.com/firebasejs/11.2.0/firebase-auth.js";
import {
  addDoc,
  collection,
  getFirestore,
  doc,
  setDoc,
  getDoc,
} from "https://www.gstatic.com/firebasejs/11.2.0/firebase-firestore.js";
import { getAnalytics } from "https://www.gstatic.com/firebasejs/11.2.0/firebase-analytics.js";

const firebaseConfig = {
  apiKey: "AIzaSyCmTMoyix09rR1fdQc24UECYXtrkkx2pUk",
  authDomain: "stopwatch-7922f.firebaseapp.com",
  databaseURL: "https://stopwatch-7922f.firebaseio.com",
  projectId: "stopwatch-7922f",
  storageBucket: "stopwatch-7922f.firebasestorage.app",
  messagingSenderId: "317708428739",
  appId: "1:317708428739:web:81c43ccdf53892f958c976",
  measurementId: "G-5QE4L0LS12",
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);
const analytics = getAnalytics(app);

export async function signup(userDetails) {
  const { firstName, lastName, userName, email, password } = userDetails;
  try {
    const userCredential = await createUserWithEmailAndPassword(
      auth,
      email,
      password
    );
    console.log(
      userCredential?.user?.uid,
      "===>> hurraayyyy user registered successfully"
    );
    const { password: myPassword, ...userDetailsWithoutPassword } = userDetails;

    // addDoc -> creates document with a unique id generated by firebase
    // const docRef = await addDoc(
    //   collection(db, "users"),
    //   userDetailsWithoutPassword
    // );

    //setDoc -> creates document with a our given unique id generated
    // Add a new document in collection "cities"
    await setDoc(doc(db, "users", userCredential?.user?.uid), {
      userDetailsWithoutPassword,
    });

    console.log("===>> hurraayyyy user ka data store hogaya");
    alert("We are going to move you towards home page");
    setTimeout(() => {
      window.location.href = "../home/home.html";
    }, 60000);
  } catch (error) {
    const errorCode = error.code;
    const errorMessage = error.message;
    console.log(errorCode, "===>> aaahhhhh registeration failed");
    console.log(errorMessage, "===>> aaahhhhh registeration failed");
    alert(errorMessage);
  }
}

export function login(email, password) {
  signInWithEmailAndPassword(auth, email, password)
    .then((userCredential) => {
      // Signed in
      const user = userCredential.user;
      console.log("===>> Welcome to the game");
      alert("Moving you to home page");
      setTimeout(() => {
        window.location.href = "../home/home.html";
      }, 10000);
      // ...
    })
    .catch((error) => {
      const errorCode = error.code;
      const errorMessage = error.message;
      console.log(errorCode, "===>> errorCode");
      console.log(errorMessage, "===>> errorMessage");
    });
}

export function loginStateObserver() {
  return new Promise(function (resolve) {
    onAuthStateChanged(auth, (user) => {
      if (user) {
        // User is signed in, see docs for a list of available properties
        // https://firebase.google.com/docs/reference/js/auth.user
        const uid = user.uid;
        console.log(uid, "==>> uid");
        resolve(uid);
        // ...
      } else {
        // User is signed out
        // ...
        console.log("==>> kaddu koi banda login nai hai");
        setTimeout(() => {
          window.location.href = "../signup/index.html";
        }, 5000);
      }
    });
  });
}

export async function getSingleDocument(uid) {
  const docRef = doc(db, "users", uid);
  const docSnap = await getDoc(docRef);

  if (docSnap.exists()) {
    // console.log("Document data:  ==>>>> ", docSnap.data());
    const { userDetailsWithoutPassword } = docSnap.data();
    console.log(userDetailsWithoutPassword, "==>>> userDetailsWithoutPassword");
    return userDetailsWithoutPassword;
  } else {
    // docSnap.data() will be undefined in this case
    console.log("No such document!");
  }
}

export async function signout() {
  try {
    await signOut(auth);
    console.log("==>> signout successfully");
    setTimeout(() => {
      window.location.href = "../login/login.html";
    }, 3000);
  } catch (error) {}
}

export async function updateProfile(
  description,
  profilePicture,
  uid,
  userDetails
) {
  await setDoc(doc(db, "users", uid), {
    userDetailsWithoutPassword: {
      ...userDetails,
      description,
      profilePicture,
    },
  });

  console.log("==>> Hurray user profile updated successfully");
  window.location.reload();
}
